#' Copyright 2014 Simon Garnier (http://www.theswarmlab.com / @sjmgarnier)
#' 
#' This script is free software: you can redistribute it and/or modify it under
#' the terms of the GNU General Public License as published by the Free Software
#' Foundation, either version 2 of the License, or (at your option) any later
#' version.
#' 
#' This script is distributed in the hope that it will be useful, but WITHOUT
#' ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#' FOR A PARTICULAR PURPOSE.
#' 
#' See the GNU General Public License for more details.
#' 
#' You should have received a copy of the GNU General Public License along with
#' this script. If not, see http://www.gnu.org/licenses/.
#' 

#' **Document title:** Custom "lattice" theme for "Wisdom of Crowds" app
#' 
#' **Date:** January 15, 2014
#' 
#' **Author:** Simon Garnier (http://www.theswarmlab.com / @sjmgarnier)
#' 
#' **Description:** This script contains a custom "lattice" theme used for all
#' the graphs generated by the accompanying "Wisdom of Crowds" app
#' 
#' Document generated with RStudio ([www.rstudio.com](http://www.rstudio.com)).
#' 

# Load libraries
require("lattice")
require("latticeExtra")

# Create theme with default options ("trellis.par.get()") and modify some of
# them to get a pretty result
my.theme <- within(trellis.par.get(), {
  
  plot.line <- within(plot.line, {
    lwd <- 3
    col <- "red"
    alpha <- 0.5
  })
  
  axis.text <- within(axis.text, {
    cex <- 1.25
  })
  
  par.xlab.text <- within(par.xlab.text, {
    cex <- 1.25
  })
  
  par.ylab.text <- within(par.ylab.text, {
    cex <- 1.25
  })
  
  par.main.text <- within(par.main.text, {
    cex <- 1.25
  })
  
  add.text <- within(add.text, {
    cex <- 1.25
  })
  
  regions <- within(regions, {
    col <- c("blue", "red")
    alpha <- 0.5
  })
  
})

my.theme.no.margins <- within(my.theme, {
  layout.heights <- within(layout.heights, {
    top.padding <- 0
    main.key.padding <- 0
    key.axis.padding <- 0
    axis.xlab.padding <- 0
    xlab.key.padding <- 0
    key.sub.padding <- 0
    bottom.padding <- 0
  })
  
  layout.widths <- within(layout.widths, {
    left.padding <- 0
    key.ylab.padding <- 0
    ylab.axis.padding <- 0
    axis.key.padding <- 0
    right.padding <- 0
  })
})


